# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('album', models.CharField(max_length=100)),
                ('album_artist', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('track_number', models.IntegerField()),
                ('track_count', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
    ]
