# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='track_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='track_count',
            field=models.IntegerField(blank=True),
        ),
    ]
