# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_auto_20160718_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='track_count',
            field=models.IntegerField(),
        ),
    ]
