# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_auto_20160718_0737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='track_id',
        ),
        migrations.AddField(
            model_name='song',
            name='persistent_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
