# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 07:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0007_auto_20160723_0702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='year',
        ),
        migrations.DeleteModel(
            name='Year',
        ),
    ]
